runtime: nodejs20
service: front-end

env: standard
instance_class: F2

# You can define environment variables here
env_variables:
  NODE_ENV: 'production'

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.6

handlers:
  # Serve all static files with the URL ending with a file extension from the Next.js static folder
  - url: /_next/static/(.*\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|json|css|js|map))$
    static_files: dist/client/_next/static/\1
    upload: dist/client/_next/static/.*\.(png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|json|css|js|map)$
    secure: always
    redirect_http_response_code: 301

  # Next.js static files, such as favicon.ico or robots.txt in the public directory
  - url: /(favicon\.ico|robots\.txt)$
    static_files: dist/client/\1
    upload: dist/client/(favicon\.ico|robots\.txt)$
    secure: always
    redirect_http_response_code: 301

  # Next.js service worker
  - url: /service-worker.js$
    static_files: dist/client/service-worker.js
    upload: dist/client/service-worker.js
    secure: always
    redirect_http_response_code: 301

  # This configures Google App Engine to route all requests to the Node server.
  - url: /.*
    script: auto
