runtime: python
env: flex
entrypoint: bash -c 'python database.py && gunicorn -b :$PORT main:app'

runtime_config:
  python_version: 3.7

env_variables:
    # postgresql+psycopg2://USER:PASSWORD@/DATABASE?host=/cloudsql/INSTANCE_CONNECTION_NAME
    DB_STRING: >-
      postgresql+psycopg2://postgres:yt@/ytubedb?host=/cloudsql/ytubedb:us-central1:ytubedb

beta_settings:
    cloud_sql_instances: ytubedb:us-central1:ytubedb

# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
  instances: 1

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
