runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
	python_version: 3


env_variables:
    # postgresql+psycopg2://USER:PASSWORD@/DATABASE?host=/cloudsql/INSTANCE_CONNECTION_NAME
    # Replace user, password, database, and instance connection name with the values obtained
    # when configuring your Cloud SQL instance.
    DB_STRING: >- 
        postgresql+psycopg2://postgres:yt@/postgres?host=/cloudsql/ytubedb:us-central1:ytubedb

# Replace project and instance with the values obtained when configuring your
# Cloud SQL instance.
beta_settings:
    cloud_sql_instances: ytubedb:us-central1:ytubedb

manual_scaling:
    instances: 1
resources:
    cpu: 1
    memory_gb: 0.5
    disk_size_gb: 10
